### ISSUE TITLE
Data from Acc,Gyro,Magneto reports same timestamp.

### ISSUE THREAD

**Issue by ljezny** [mbientlab/MetaWear-SDK-iOS-macOS-tvOS#1]
Hi,

i've updated to 2.8.3 and found this weird issue. I'm tracking MBLAccelerometerData and it is reported with the same timestamp. (everytime 3 events with different data in row has same timestamp, then another 3 events has same timestamp).

Version 2.8.2 works just fine.

Feel free to contact me for more info if needed

**Comment by sschiffli** [comment]
I guess you found out that at higher frequencies we pack together multiple samples to improve bandwidth.  A side effect of this is that we loose precision on timestamps, so 3 will be grouped together since they all arrive to the iDevice at the same time.

**Comment by ljezny** [comment]
Hi, yes, high frequency was the issue.
