### ISSUE TITLE
"No such module 'MetaWearCpp'" error in StarterProject when building for iOS

### ISSUE THREAD

**Issue by rednebmas** [mbientlab/MetaWear-SDK-iOS-macOS-tvOS#12]
The error is occurring in the file `DeviceInformation.swift` under Metaware/Core. 

Xcode version: 11.2.1
Cocoapods version: 1.8.4

Let me know if you need any more information.

**Comment by lkasso** [comment]
This is not an issue. You simply have not added your pods correctly. Please DO NOT post issues in this repo unless it has been verified as an issue in our forums.
