### ISSUE TITLE
option for static lib, with bitcode?

### ISSUE THREAD

**Issue by sjmerel** [mbientlab/MetaWear-SDK-iOS-macOS-tvOS#2]
It would be great to have an option to build a static library with bitcode.  The current framework is a dylib without bitcode; I'm not sure whether bitcode is possible in a dylib, but I was unable to get it to build with bitcode unless I switched to a static lib.

**Comment by sschiffli** [comment]
Our primary method of integrating the library is with cocoapods, which sets up the project to build with bitcode.  See https://github.com/mbientlab/Metawear-SampleiOSApp as an example.
