### ISSUE TITLE
Thread dump on calling MBLMetaWearManager.shared()

### ISSUE THREAD

**Issue by smilanko** [mbientlab/MetaWear-SDK-iOS-macOS-tvOS#4]
I am creating a CLI Application, that will run for MACOSX.
I want to connect to the MetaWear sensors to just log data to a file.

I am following the guide on here: https://mbientlab.com/iosdocs/latest/metawear_manager.html

If I instantiate a manager class, and attempt a connection alike this, I get a Thread dump stating:

    Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

i.e The following line will cause a Thread dump above:
    
    MBLMetaWearManager.shared();

My main class:

    import Foundation

    let runLoop = RunLoop.current;
    let distantFuture = Date.distantFuture;

    print("### we are in the create");
    let starter = MetaWearStarter();
    print("### we are after the create");

    while (runLoop.run(mode: RunLoopMode.defaultRunLoopMode, before:    distantFuture)){
        print("### listening for a metawear device");
    }

My MetaWearStarter class:

    import Foundation

    import MetaWear

    class MetaWearStarter : NSObject {

        override init() {
            super.init();
            print("### we are in the init");
            startConnection();
        }

        func startConnection() {
            print("##### connection call was made");
            let manager = MBLMetaWearManager.shared();
            maanger.startScanForMetaWears() { array in
            print("### connection scan was complete")    
            // Hooray! We found a MetaWear board, so stop scanning for more
                MBLMetaWearManager.shared().stopScan()
                // Connect to the board we found
                if let device = array.first {
                    device.connectAsync().success() { _ in
                        print("#### we connected to a device");
                        }.failure() { error in
                            print("### unable to connect");
                    }
                }
            }
        }

    }

I have a stack question opened here: https://stackoverflow.com/questions/46435965/metawear-cli-application-on-macosx

What exactly am I doing wrong in following the guide?

**Comment by sschiffli** [comment]
The code as you have listed looks correct.  If I had to guess, your issue is probably with the environment.

MacOS command line tools behave don't play nice with CocoaPods frameworks.  In order for it to work, you need to remove the `use_frameworks!` line from your Podfile, then create a bridging header file and add `#import <MetaWear/MetaWear.h>`.  (Also then remove `import MetaWear`)

**Comment by smilanko** [comment]
Can you give an example of this bridging header file? I am following the other two suggestions you make, but this one is a bit beyond my understanding.

**Comment by sschiffli** [comment]
Probably the easiest is to create a new file (cmd-N), choose Cocoa Class, and select language as Objective-C.  Xcode will ask you to automatically create a bridging header, simply say yes and you will have one.
