### ISSUE TITLE
Apple Notification Center Service (ANCS)

### ISSUE THREAD

**Issue by cl3m** [mbientlab/MetaWear-SDK-iOS-macOS-tvOS#8]
Hi,

The version 3 does not have any ANCS code. Are you planning to bring this functionality back? 
The version develop2.0 has some code, but it does not work. It never finish the programming sequence when using the device.ancs object.

Best regards,

Clément

**Comment by sschiffli** [comment]
Clément,

Sorry but we had to drop ANCS due to high complexity and low demand.  It is currently not on our roadmap, but it may come back in the future.  The best thing would be to post this request at our community page: https://mbientlab.com/community/

Thanks,
Stephen
