### ISSUE TITLE
Bookmark  "downloadLogAndStopLoggingAsync" method in Objective C giving an error ?

### ISSUE THREAD

**Issue by subinrevi** [mbientlab/MetaWear-SDK-iOS-macOS-tvOS#9]
`[[[self.device.accelerometer.dataReadyEvent downloadLogAndStopLoggingAsync:YES progressHandler:^(float number) {
      
    }] success:^(NSArray<MBLAccelerometerData *> * _Nonnull array) {
        
    }] failure:^(NSError * _Nonnull error) {
        
    }];`

The above code is giving the error "No visible @interface for 'BFTask<NSArray<MBLAccelerometerData *> *>' declares the selector 'success:'". Please suggest the correct method to use in Objective C

**Comment by scaryghost** [comment]
We do not support objective-c as of the v3 release.

**Comment by scaryghost** [comment]
We no longer support objective-c.  Update your project to use the v3 releases or read the BFTask obj-c documentation.

**Comment by asangadev** [comment]
Make sure you import 
```
#import "BFTask+MBLExtensions.h"
```
